#ifndef VERSION_H
#define VERSION_H

// !!! DO NOT EDIT THIS FILE !!!
// This file is automatically generated by GitHub Actions

#define VER_RUN_ID 200489790
#define VER_RUN_ID_STR "200489790"
#define VER_RUN_NUM 5
#define VER_RUN_NUM_STR "5"
#define VER_BRANCH_STR "master"
#define VER_YEAR 20
#define VER_YEAR_STR "20"
#define VER_MON 08
#define VER_MON_STR "08"
#define VER_DATE 09
#define VER_DATE_STR "09"
#define VER_HOUR 00
#define VER_HOUR_STR "00"
#define VER_MIN 19
#define VER_MIN_STR "19"
#define VER_SEC 28
#define VER_SEC_STR "28"

#endif
