#ifndef VERSION_H
#define VERSION_H

// !!! DO NOT EDIT THIS FILE !!!
// This file is automatically generated by GitHub Actions

#define VER_RUN_ID 202932171
#define VER_RUN_ID_STR "202932171"
#define VER_RUN_NUM 8
#define VER_RUN_NUM_STR "8"
#define VER_BRANCH_STR "master"
#define VER_YEAR 20
#define VER_YEAR_STR "20"
#define VER_MON 08
#define VER_MON_STR "08"
#define VER_DATE 11
#define VER_DATE_STR "11"
#define VER_HOUR 03
#define VER_HOUR_STR "03"
#define VER_MIN 45
#define VER_MIN_STR "45"
#define VER_SEC 20
#define VER_SEC_STR "20"

#endif
